// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChain(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChain'](arg1, arg2, arg3);
}

export function CreateCollection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3, arg4);
}

export function CreatePrompt(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteChain(arg1) {
  return window['go']['main']['App']['DeleteChain'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetChains() {
  return window['go']['main']['App']['GetChains']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetPrompts(arg1) {
  return window['go']['main']['App']['GetPrompts'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetVersions(arg1) {
  return window['go']['main']['App']['GetVersions'](arg1);
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function RecordUse(arg1) {
  return window['go']['main']['App']['RecordUse'](arg1);
}

export function RenderPrompt(arg1, arg2) {
  return window['go']['main']['App']['RenderPrompt'](arg1, arg2);
}

export function RestoreVersion(arg1, arg2) {
  return window['go']['main']['App']['RestoreVersion'](arg1, arg2);
}

export function SaveVariables(arg1, arg2) {
  return window['go']['main']['App']['SaveVariables'](arg1, arg2);
}

export function SetRating(arg1, arg2) {
  return window['go']['main']['App']['SetRating'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function UpdateCollection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}
