// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateChain(arg1:string,arg2:string,arg3:Array<number>):Promise<main.PromptChain>;

export function CreateCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Collection>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:any,arg5:string,arg6:string,arg7:Array<number>):Promise<main.Prompt>;

export function CreateTag(arg1:string,arg2:string):Promise<main.Tag>;

export function DeleteChain(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeletePrompt(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function ExportData():Promise<string>;

export function GetChains():Promise<Array<main.PromptChain>>;

export function GetCollections():Promise<Array<main.Collection>>;

export function GetPrompt(arg1:number):Promise<main.Prompt>;

export function GetPrompts(arg1:string):Promise<Array<main.Prompt>>;

export function GetStats():Promise<main.Stats>;

export function GetTags():Promise<Array<main.Tag>>;

export function GetVersions(arg1:number):Promise<Array<main.PromptVersion>>;

export function ImportData(arg1:string):Promise<void>;

export function RecordUse(arg1:number):Promise<void>;

export function RenderPrompt(arg1:number,arg2:Record<string, string>):Promise<string>;

export function RestoreVersion(arg1:number,arg2:number):Promise<void>;

export function SaveVariables(arg1:number,arg2:Array<main.Variable>):Promise<void>;

export function SetRating(arg1:number,arg2:number):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdatePrompt(arg1:number,arg2:string,arg3:string,arg4:string,arg5:any,arg6:string,arg7:string,arg8:Array<number>,arg9:string):Promise<void>;
